namespace Trung_tam_quan_ly_ngoai_ngu;
partial class FrmTeacherDashboard
{
    private System.ComponentModel.IContainer components=null; private Panel pnlSidebarTeacher; private Panel pnlTopbarTeacher; private Panel pnlContentHostTeacher; private Panel pnlDashboardHome; private Label lblCurrentRoleTeacher; private Label lblCurrentUserTeacher; private Button btnLogoutTeacher; private Button btnMenuTeacherDashboard; private Button btnMenuTeachingClasses; private Button btnMenuClassStudentList; private Button btnMenuAttendance; private Button btnMenuScoreEntry; private Label lblTeacherDashboardTitle; private Panel pnlTeachingClassesCount; private Panel pnlTeachingStudentCount; private Panel pnlTeachingTodaySessions; private Panel pnlTeachingPendingScores; private Label lblTeachingClassesCountValue; private Label lblTeachingStudentCountValue; private Label lblTeachingTodaySessionsValue; private Label lblTeachingPendingScoresValue; private DataGridView dgvTeacherClassOverview;
    protected override void Dispose(bool disposing){ if(disposing && components!=null) components.Dispose(); base.Dispose(disposing);} 
    private void InitializeComponent(){ pnlSidebarTeacher=new Panel(); pnlTopbarTeacher=new Panel(); pnlContentHostTeacher=new Panel(); pnlDashboardHome=new Panel(); lblCurrentRoleTeacher=new Label(); lblCurrentUserTeacher=new Label(); btnLogoutTeacher=new Button(); btnMenuTeacherDashboard=new Button(); btnMenuTeachingClasses=new Button(); btnMenuClassStudentList=new Button(); btnMenuAttendance=new Button(); btnMenuScoreEntry=new Button(); lblTeacherDashboardTitle=new Label(); pnlTeachingClassesCount=new Panel(); pnlTeachingStudentCount=new Panel(); pnlTeachingTodaySessions=new Panel(); pnlTeachingPendingScores=new Panel(); lblTeachingClassesCountValue=new Label(); lblTeachingStudentCountValue=new Label(); lblTeachingTodaySessionsValue=new Label(); lblTeachingPendingScoresValue=new Label(); dgvTeacherClassOverview=new DataGridView(); ((System.ComponentModel.ISupportInitialize)dgvTeacherClassOverview).BeginInit(); SuspendLayout();
        pnlSidebarTeacher.BackColor=Color.FromArgb(230,246,255); pnlSidebarTeacher.Dock=DockStyle.Left; pnlSidebarTeacher.Width=256; var buttons=new[]{btnMenuTeacherDashboard,btnMenuTeachingClasses,btnMenuClassStudentList,btnMenuAttendance,btnMenuScoreEntry}; string[] texts={"Dashboard gi?ng d?y","L?p ?ang d?y","DS h?c viên l?p","Ði?m danh","Nh?p ?i?m"}; for(int i=0;i<buttons.Length;i++){ buttons[i].Location=new Point(24,120+(i*44)); buttons[i].Size=new Size(208,40); buttons[i].Text=texts[i]; pnlSidebarTeacher.Controls.Add(buttons[i]); }
        pnlTopbarTeacher.BackColor=Color.White; pnlTopbarTeacher.Dock=DockStyle.Top; pnlTopbarTeacher.Height=68; lblCurrentRoleTeacher.Location=new Point(24,24); lblCurrentRoleTeacher.AutoSize=true; lblCurrentUserTeacher.Location=new Point(860,24); lblCurrentUserTeacher.AutoSize=true; btnLogoutTeacher.Location=new Point(1040,18); btnLogoutTeacher.Size=new Size(110,32); btnLogoutTeacher.Text="Ðang xu?t"; pnlTopbarTeacher.Controls.AddRange(new Control[]{lblCurrentRoleTeacher,lblCurrentUserTeacher,btnLogoutTeacher});
        pnlContentHostTeacher.Dock=DockStyle.Fill; pnlContentHostTeacher.Padding=new Padding(18); pnlContentHostTeacher.Controls.Add(pnlDashboardHome); pnlDashboardHome.Dock=DockStyle.Fill; pnlDashboardHome.Controls.AddRange(new Control[]{dgvTeacherClassOverview,pnlTeachingPendingScores,pnlTeachingTodaySessions,pnlTeachingStudentCount,pnlTeachingClassesCount,lblTeacherDashboardTitle});
        lblTeacherDashboardTitle.AutoSize=true; lblTeacherDashboardTitle.Font=AppTheme.FontTitle; lblTeacherDashboardTitle.Location=new Point(12,12); lblTeacherDashboardTitle.Text="Dashboard gi?ng d?y"; pnlTeachingClassesCount.BorderStyle=BorderStyle.FixedSingle; pnlTeachingClassesCount.Location=new Point(16,64); pnlTeachingClassesCount.Size=new Size(240,96); pnlTeachingClassesCount.Controls.Add(lblTeachingClassesCountValue); pnlTeachingStudentCount.BorderStyle=BorderStyle.FixedSingle; pnlTeachingStudentCount.Location=new Point(272,64); pnlTeachingStudentCount.Size=new Size(240,96); pnlTeachingStudentCount.Controls.Add(lblTeachingStudentCountValue); pnlTeachingTodaySessions.BorderStyle=BorderStyle.FixedSingle; pnlTeachingTodaySessions.Location=new Point(528,64); pnlTeachingTodaySessions.Size=new Size(240,96); pnlTeachingTodaySessions.Controls.Add(lblTeachingTodaySessionsValue); pnlTeachingPendingScores.BorderStyle=BorderStyle.FixedSingle; pnlTeachingPendingScores.Location=new Point(784,64); pnlTeachingPendingScores.Size=new Size(240,96); pnlTeachingPendingScores.Controls.Add(lblTeachingPendingScoresValue); foreach(var lbl in new[]{lblTeachingClassesCountValue,lblTeachingStudentCountValue,lblTeachingTodaySessionsValue,lblTeachingPendingScoresValue}){ lbl.Dock=DockStyle.Fill; lbl.TextAlign=ContentAlignment.MiddleCenter; lbl.Font=AppTheme.FontKpi; } dgvTeacherClassOverview.Location=new Point(16,184); dgvTeacherClassOverview.Size=new Size(1008,420); dgvTeacherClassOverview.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill; dgvTeacherClassOverview.RowHeadersVisible=false; dgvTeacherClassOverview.Name="dgvTeacherClassOverview";
        AutoScaleMode=AutoScaleMode.None; ClientSize=new Size(920,580); Controls.AddRange(new Control[]{pnlContentHostTeacher,pnlTopbarTeacher,pnlSidebarTeacher}); Name="FrmTeacherDashboard"; ((System.ComponentModel.ISupportInitialize)dgvTeacherClassOverview).EndInit(); ResumeLayout(false);
    }
}

