namespace Trung_tam_quan_ly_ngoai_ngu;
partial class FrmCourseManagement
{
    private System.ComponentModel.IContainer components=null; private Panel pnlCourseFilterCard; private TextBox txtCourseKeyword; private ComboBox cboCourseStatusFilter; private Button btnSearchCourse; private Button btnRefreshCourse; private DataGridView dgvCourseList; private GroupBox grpCourseInfo; private Button btnCreateCourse; private Button btnSaveCourse; private Button btnUpdateCourse; private Button btnDeleteCourse;
    protected override void Dispose(bool disposing){ if(disposing && components!=null) components.Dispose(); base.Dispose(disposing);} 
    private void InitializeComponent(){ pnlCourseFilterCard=new Panel(); txtCourseKeyword=new TextBox(); cboCourseStatusFilter=new ComboBox(); btnSearchCourse=new Button(); btnRefreshCourse=new Button(); dgvCourseList=new DataGridView(); grpCourseInfo=new GroupBox(); btnCreateCourse=new Button(); btnSaveCourse=new Button(); btnUpdateCourse=new Button(); btnDeleteCourse=new Button(); ((System.ComponentModel.ISupportInitialize)dgvCourseList).BeginInit(); SuspendLayout();
        pnlCourseFilterCard.BorderStyle=BorderStyle.FixedSingle; pnlCourseFilterCard.Location=new Point(8,8); pnlCourseFilterCard.Size=new Size(1120,80); txtCourseKeyword.Location=new Point(16,24); txtCourseKeyword.Size=new Size(260,23); txtCourseKeyword.Name="txtCourseKeyword"; cboCourseStatusFilter.Location=new Point(292,24); cboCourseStatusFilter.Size=new Size(180,23); cboCourseStatusFilter.Items.AddRange(new object[]{"T?t c?","C̣n m?","T?m d?ng"}); cboCourseStatusFilter.Name="cboCourseStatusFilter"; btnSearchCourse.Location=new Point(488,22); btnSearchCourse.Size=new Size(90,28); btnSearchCourse.Text="T́m"; btnRefreshCourse.Location=new Point(590,22); btnRefreshCourse.Size=new Size(90,28); btnRefreshCourse.Text="Làm m?i"; pnlCourseFilterCard.Controls.AddRange(new Control[]{txtCourseKeyword,cboCourseStatusFilter,btnSearchCourse,btnRefreshCourse});
        dgvCourseList.Location=new Point(8,104); dgvCourseList.Size=new Size(600,540); dgvCourseList.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill; dgvCourseList.RowHeadersVisible=false; dgvCourseList.Name="dgvCourseList"; grpCourseInfo.Location=new Point(624,104); grpCourseInfo.Size=new Size(504,420); grpCourseInfo.Text="Thông tin khóa h?c"; grpCourseInfo.Name="grpCourseInfo";
        btnCreateCourse.Location=new Point(624,540); btnCreateCourse.Size=new Size(90,32); btnCreateCourse.Text="Thêm"; btnCreateCourse.Name="btnCreateCourse"; btnSaveCourse.Location=new Point(726,540); btnSaveCourse.Size=new Size(90,32); btnSaveCourse.Text="Luu"; btnSaveCourse.Name="btnSaveCourse"; btnUpdateCourse.Location=new Point(828,540); btnUpdateCourse.Size=new Size(90,32); btnUpdateCourse.Text="C?p nh?t"; btnUpdateCourse.Name="btnUpdateCourse"; btnDeleteCourse.Location=new Point(930,540); btnDeleteCourse.Size=new Size(90,32); btnDeleteCourse.Text="Xóa"; btnDeleteCourse.Name="btnDeleteCourse";
        Controls.AddRange(new Control[]{pnlCourseFilterCard,dgvCourseList,grpCourseInfo,btnCreateCourse,btnSaveCourse,btnUpdateCourse,btnDeleteCourse}); ClientSize=new Size(1140,650); Name="FrmCourseManagement"; ((System.ComponentModel.ISupportInitialize)dgvCourseList).EndInit(); ResumeLayout(false);
    }
}
