namespace Trung_tam_quan_ly_ngoai_ngu;
partial class FrmDebtTracking
{
    private System.ComponentModel.IContainer components=null; private Panel pnlDebtFilterCard; private ComboBox cboDebtCourseFilter; private ComboBox cboDebtClassFilter; private DateTimePicker dtpDebtFromDate; private DateTimePicker dtpDebtToDate; private Button btnSearchDebt; private Button btnRefreshDebt; private Button btnExportDebt; private Panel pnlDebtTotalCount; private Panel pnlDebtTotalAmount; private Label lblDebtTotalCountValue; private Label lblDebtTotalAmountValue; private DataGridView dgvDebtTrackingList; private Button btnOpenTuitionFromDebt; private Button btnViewReceiptHistory;
    protected override void Dispose(bool disposing){ if(disposing && components!=null) components.Dispose(); base.Dispose(disposing);} 
    private void InitializeComponent(){ pnlDebtFilterCard=new Panel(); cboDebtCourseFilter=new ComboBox(); cboDebtClassFilter=new ComboBox(); dtpDebtFromDate=new DateTimePicker(); dtpDebtToDate=new DateTimePicker(); btnSearchDebt=new Button(); btnRefreshDebt=new Button(); btnExportDebt=new Button(); pnlDebtTotalCount=new Panel(); pnlDebtTotalAmount=new Panel(); lblDebtTotalCountValue=new Label(); lblDebtTotalAmountValue=new Label(); dgvDebtTrackingList=new DataGridView(); btnOpenTuitionFromDebt=new Button(); btnViewReceiptHistory=new Button(); ((System.ComponentModel.ISupportInitialize)dgvDebtTrackingList).BeginInit(); SuspendLayout();
        pnlDebtFilterCard.BorderStyle=BorderStyle.FixedSingle; pnlDebtFilterCard.Location=new Point(8,8); pnlDebtFilterCard.Size=new Size(1120,80); cboDebtCourseFilter.Location=new Point(16,24); cboDebtCourseFilter.Size=new Size(160,23); cboDebtCourseFilter.Items.AddRange(new object[]{"T?t c?","English Foundation","Tin h?c co b?n"}); cboDebtCourseFilter.Name="cboDebtCourseFilter"; cboDebtClassFilter.Location=new Point(192,24); cboDebtClassFilter.Size=new Size(160,23); cboDebtClassFilter.Items.AddRange(new object[]{"T?t c?","ENG-A1-01","TIN-CB-03"}); cboDebtClassFilter.Name="cboDebtClassFilter"; dtpDebtFromDate.Location=new Point(368,24); dtpDebtFromDate.Name="dtpDebtFromDate"; dtpDebtToDate.Location=new Point(554,24); dtpDebtToDate.Name="dtpDebtToDate"; btnSearchDebt.Location=new Point(740,22); btnSearchDebt.Size=new Size(90,28); btnSearchDebt.Text="T́m"; btnRefreshDebt.Location=new Point(842,22); btnRefreshDebt.Size=new Size(90,28); btnRefreshDebt.Text="Làm m?i"; btnExportDebt.Location=new Point(944,22); btnExportDebt.Size=new Size(110,28); btnExportDebt.Text="Xu?t"; pnlDebtFilterCard.Controls.AddRange(new Control[]{cboDebtCourseFilter,cboDebtClassFilter,dtpDebtFromDate,dtpDebtToDate,btnSearchDebt,btnRefreshDebt,btnExportDebt});
        pnlDebtTotalCount.BorderStyle=BorderStyle.FixedSingle; pnlDebtTotalCount.Location=new Point(8,104); pnlDebtTotalCount.Size=new Size(260,84); pnlDebtTotalCount.Controls.Add(lblDebtTotalCountValue); pnlDebtTotalAmount.BorderStyle=BorderStyle.FixedSingle; pnlDebtTotalAmount.Location=new Point(284,104); pnlDebtTotalAmount.Size=new Size(260,84); pnlDebtTotalAmount.Controls.Add(lblDebtTotalAmountValue); foreach(var lbl in new[]{lblDebtTotalCountValue,lblDebtTotalAmountValue}){ lbl.Dock=DockStyle.Fill; lbl.TextAlign=ContentAlignment.MiddleCenter; lbl.Font=AppTheme.FontKpi; }
        dgvDebtTrackingList.Location=new Point(8,208); dgvDebtTrackingList.Size=new Size(1120,384); dgvDebtTrackingList.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill; dgvDebtTrackingList.RowHeadersVisible=false; dgvDebtTrackingList.Name="dgvDebtTrackingList";
        btnOpenTuitionFromDebt.Location=new Point(8,608); btnOpenTuitionFromDebt.Size=new Size(120,32); btnOpenTuitionFromDebt.Text="Thu ti?n nhanh"; btnOpenTuitionFromDebt.Name="btnOpenTuitionFromDebt"; btnViewReceiptHistory.Location=new Point(140,608); btnViewReceiptHistory.Size=new Size(160,32); btnViewReceiptHistory.Text="Xem l?ch s? biên nh?n"; btnViewReceiptHistory.Name="btnViewReceiptHistory";
        Controls.AddRange(new Control[]{pnlDebtFilterCard,pnlDebtTotalCount,pnlDebtTotalAmount,dgvDebtTrackingList,btnOpenTuitionFromDebt,btnViewReceiptHistory}); ClientSize=new Size(1140,650); Name="FrmDebtTracking"; ((System.ComponentModel.ISupportInitialize)dgvDebtTrackingList).EndInit(); ResumeLayout(false);
    }
}
