namespace Trung_tam_quan_ly_ngoai_ngu;
partial class FrmEnrollment
{
    private System.ComponentModel.IContainer components=null; private GroupBox grpEnrollmentStudentSelect; private GroupBox grpEnrollmentClassSelect; private GroupBox grpEnrollmentSummary; private DataGridView dgvEnrollmentStudentList; private DataGridView dgvEnrollmentClassList; private DateTimePicker dtpEnrollmentDate; private TextBox txtEnrollmentOriginalFee; private TextBox txtEnrollmentDiscount; private TextBox txtEnrollmentFinalFee; private ComboBox cboEnrollmentStatus; private TextBox txtEnrollmentNote; private Button btnCreateEnrollment; private Button btnRefreshEnrollment; private Button btnOpenTuitionReceipt;
    protected override void Dispose(bool disposing){ if(disposing && components!=null) components.Dispose(); base.Dispose(disposing);} 
    private void InitializeComponent(){ grpEnrollmentStudentSelect=new GroupBox(); grpEnrollmentClassSelect=new GroupBox(); grpEnrollmentSummary=new GroupBox(); dgvEnrollmentStudentList=new DataGridView(); dgvEnrollmentClassList=new DataGridView(); dtpEnrollmentDate=new DateTimePicker(); txtEnrollmentOriginalFee=new TextBox(); txtEnrollmentDiscount=new TextBox(); txtEnrollmentFinalFee=new TextBox(); cboEnrollmentStatus=new ComboBox(); txtEnrollmentNote=new TextBox(); btnCreateEnrollment=new Button(); btnRefreshEnrollment=new Button(); btnOpenTuitionReceipt=new Button(); ((System.ComponentModel.ISupportInitialize)dgvEnrollmentStudentList).BeginInit(); ((System.ComponentModel.ISupportInitialize)dgvEnrollmentClassList).BeginInit(); SuspendLayout();
        grpEnrollmentStudentSelect.Location=new Point(8,8); grpEnrollmentStudentSelect.Size=new Size(360,634); grpEnrollmentStudentSelect.Text="1. Ch?n h?c viên"; grpEnrollmentStudentSelect.Controls.Add(dgvEnrollmentStudentList); dgvEnrollmentStudentList.Dock=DockStyle.Fill; dgvEnrollmentStudentList.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill; dgvEnrollmentStudentList.RowHeadersVisible=false; dgvEnrollmentStudentList.Name="dgvEnrollmentStudentList";
        grpEnrollmentClassSelect.Location=new Point(384,8); grpEnrollmentClassSelect.Size=new Size(360,634); grpEnrollmentClassSelect.Text="2. Ch?n khóa / l?p"; grpEnrollmentClassSelect.Controls.Add(dgvEnrollmentClassList); dgvEnrollmentClassList.Dock=DockStyle.Fill; dgvEnrollmentClassList.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill; dgvEnrollmentClassList.RowHeadersVisible=false; dgvEnrollmentClassList.Name="dgvEnrollmentClassList";
        grpEnrollmentSummary.Location=new Point(760,8); grpEnrollmentSummary.Size=new Size(368,634); grpEnrollmentSummary.Text="3. Tóm t?t ghi danh"; dtpEnrollmentDate.Location=new Point(24,40); dtpEnrollmentDate.Name="dtpEnrollmentDate"; txtEnrollmentOriginalFee.Location=new Point(24,88); txtEnrollmentOriginalFee.Size=new Size(220,23); txtEnrollmentOriginalFee.Name="txtEnrollmentOriginalFee"; txtEnrollmentDiscount.Location=new Point(24,136); txtEnrollmentDiscount.Size=new Size(220,23); txtEnrollmentDiscount.Name="txtEnrollmentDiscount"; txtEnrollmentFinalFee.Location=new Point(24,184); txtEnrollmentFinalFee.Size=new Size(220,23); txtEnrollmentFinalFee.Name="txtEnrollmentFinalFee"; cboEnrollmentStatus.Location=new Point(24,232); cboEnrollmentStatus.Size=new Size(220,23); cboEnrollmentStatus.Items.AddRange(new object[]{"Đang h?c","B?o luu"}); cboEnrollmentStatus.Name="cboEnrollmentStatus"; txtEnrollmentNote.Location=new Point(24,280); txtEnrollmentNote.Size=new Size(300,23); txtEnrollmentNote.Name="txtEnrollmentNote"; btnCreateEnrollment.Location=new Point(24,328); btnCreateEnrollment.Size=new Size(110,32); btnCreateEnrollment.Text="T?o ghi danh"; btnCreateEnrollment.Name="btnCreateEnrollment"; btnRefreshEnrollment.Location=new Point(146,328); btnRefreshEnrollment.Size=new Size(110,32); btnRefreshEnrollment.Text="Làm m?i"; btnRefreshEnrollment.Name="btnRefreshEnrollment"; btnOpenTuitionReceipt.Location=new Point(24,376); btnOpenTuitionReceipt.Size=new Size(160,32); btnOpenTuitionReceipt.Text="Chuy?n sang thu phí"; btnOpenTuitionReceipt.Name="btnOpenTuitionReceipt"; grpEnrollmentSummary.Controls.AddRange(new Control[]{dtpEnrollmentDate,txtEnrollmentOriginalFee,txtEnrollmentDiscount,txtEnrollmentFinalFee,cboEnrollmentStatus,txtEnrollmentNote,btnCreateEnrollment,btnRefreshEnrollment,btnOpenTuitionReceipt});
        Controls.AddRange(new Control[]{grpEnrollmentStudentSelect,grpEnrollmentClassSelect,grpEnrollmentSummary}); ClientSize=new Size(1140,650); Name="FrmEnrollment"; ((System.ComponentModel.ISupportInitialize)dgvEnrollmentStudentList).EndInit(); ((System.ComponentModel.ISupportInitialize)dgvEnrollmentClassList).EndInit(); ResumeLayout(false);
    }
}
