namespace Trung_tam_quan_ly_ngoai_ngu;
partial class FrmTeacherManagement
{
    private System.ComponentModel.IContainer components=null; private Panel pnlTeacherFilterCard; private TextBox txtTeacherKeyword; private ComboBox cboTeacherStatusFilter; private Button btnSearchTeacher; private Button btnRefreshTeacher; private DataGridView dgvTeacherList; private GroupBox grpTeacherInfo; private ErrorProvider errTeacher; private Button btnCreateTeacher; private Button btnSaveTeacher; private Button btnUpdateTeacher; private Button btnDeleteTeacher;
    protected override void Dispose(bool disposing){ if(disposing && components!=null) components.Dispose(); base.Dispose(disposing);} 
    private void InitializeComponent(){ components=new System.ComponentModel.Container(); pnlTeacherFilterCard=new Panel(); txtTeacherKeyword=new TextBox(); cboTeacherStatusFilter=new ComboBox(); btnSearchTeacher=new Button(); btnRefreshTeacher=new Button(); dgvTeacherList=new DataGridView(); grpTeacherInfo=new GroupBox(); errTeacher=new ErrorProvider(components); btnCreateTeacher=new Button(); btnSaveTeacher=new Button(); btnUpdateTeacher=new Button(); btnDeleteTeacher=new Button(); ((System.ComponentModel.ISupportInitialize)dgvTeacherList).BeginInit(); ((System.ComponentModel.ISupportInitialize)errTeacher).BeginInit(); SuspendLayout();
        pnlTeacherFilterCard.BorderStyle=BorderStyle.FixedSingle; pnlTeacherFilterCard.Location=new Point(8,8); pnlTeacherFilterCard.Size=new Size(1120,80); txtTeacherKeyword.Location=new Point(16,24); txtTeacherKeyword.Size=new Size(260,23); txtTeacherKeyword.Name="txtTeacherKeyword"; cboTeacherStatusFilter.Location=new Point(292,24); cboTeacherStatusFilter.Size=new Size(180,23); cboTeacherStatusFilter.Items.AddRange(new object[]{"T?t c?","Đang d?y","T?m ngh?"}); cboTeacherStatusFilter.Name="cboTeacherStatusFilter"; btnSearchTeacher.Location=new Point(488,22); btnSearchTeacher.Size=new Size(90,28); btnSearchTeacher.Text="T́m"; btnRefreshTeacher.Location=new Point(590,22); btnRefreshTeacher.Size=new Size(90,28); btnRefreshTeacher.Text="Làm m?i"; pnlTeacherFilterCard.Controls.AddRange(new Control[]{txtTeacherKeyword,cboTeacherStatusFilter,btnSearchTeacher,btnRefreshTeacher});
        dgvTeacherList.Location=new Point(8,104); dgvTeacherList.Size=new Size(600,540); dgvTeacherList.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill; dgvTeacherList.RowHeadersVisible=false; dgvTeacherList.Name="dgvTeacherList"; grpTeacherInfo.Location=new Point(624,104); grpTeacherInfo.Size=new Size(504,420); grpTeacherInfo.Text="Thông tin giáo viên"; grpTeacherInfo.Name="grpTeacherInfo";
        btnCreateTeacher.Location=new Point(624,540); btnCreateTeacher.Size=new Size(90,32); btnCreateTeacher.Text="Thêm"; btnCreateTeacher.Name="btnCreateTeacher"; btnSaveTeacher.Location=new Point(726,540); btnSaveTeacher.Size=new Size(90,32); btnSaveTeacher.Text="Luu"; btnSaveTeacher.Name="btnSaveTeacher"; btnUpdateTeacher.Location=new Point(828,540); btnUpdateTeacher.Size=new Size(90,32); btnUpdateTeacher.Text="C?p nh?t"; btnUpdateTeacher.Name="btnUpdateTeacher"; btnDeleteTeacher.Location=new Point(930,540); btnDeleteTeacher.Size=new Size(90,32); btnDeleteTeacher.Text="Xóa"; btnDeleteTeacher.Name="btnDeleteTeacher";
        Controls.AddRange(new Control[]{pnlTeacherFilterCard,dgvTeacherList,grpTeacherInfo,btnCreateTeacher,btnSaveTeacher,btnUpdateTeacher,btnDeleteTeacher}); ClientSize=new Size(1140,650); Name="FrmTeacherManagement"; ((System.ComponentModel.ISupportInitialize)dgvTeacherList).EndInit(); ((System.ComponentModel.ISupportInitialize)errTeacher).EndInit(); ResumeLayout(false);
    }
}
